#pragma once

namespace Proximity::Graphics::Defaults
{
	enum DefaultRasterizerState
	{
		// FILL
		CULL_NONE = 0,
		CULL_FRONT,
		CULL_BACK,

		// WIREFRAME
		WIREFRAME,

		RASTERIZER_STATE_COUNT
	};

	enum EDefaultBlendState
	{
		DISABLED,
		ADDITIVE_COLOR,
		ALPHA_BLEND,

		BLEND_STATE_COUNT
	};

	enum EDefaultSamplerState
	{
		POINT_SAMPLER,
		LINEAR_FILTER_SAMPLER_WRAP_UVW,
		LINEAR_FILTER_SAMPLER,

		WRAP_SAMPLER,

		ANISOTROPIC_1_CLAMPED_SAMPLER,
		ANISOTROPIC_2_CLAMPED_SAMPLER,
		ANISOTROPIC_4_CLAMPED_SAMPLER,
		ANISOTROPIC_16_CLAMPED_SAMPLER,

		ANISOTROPIC_1_WRAPPED_SAMPLER,
		ANISOTROPIC_2_WRAPPED_SAMPLER,
		ANISOTROPIC_4_WRAPPED_SAMPLER,
		ANISOTROPIC_16_WRAPPED_SAMPLER,

		SAMPLER_STATE_COUNT
	};


	enum EDefaultDepthStencilState
	{
		DEPTH_STENCIL_WRITE,
		DEPTH_STENCIL_DISABLED,
		DEPTH_WRITE,
		STENCIL_WRITE,
		DEPTH_TEST_ONLY,
		// TODO: add more depth stencil states as needed

		DEPTH_STENCIL_STATE_COUNT
	};
}
